
close all
clear

m = Model.fromFile( ...
    "model-source/nonlinearBkw.model" ...
    , allowExogenous=true ...
);



d = struct();
d.x = Series(1:10, 10);
d.y = Series(0:10, 10);
d.z = Series(1:10, 15);
d.z(11) = 20;
d.wy = Series(1:10, @rand);

s = simulate( ...
    m, d, 1:10 ...
    , method="stacked" ...
    , startIterationsFrom="data" ...
    , terminal="data" ...
    , prependInput=true ...
    , appendInput=true ...
);

ch = Chartpack();
ch.Range = 0:11;
ch + ["x", "y", "z", "wy"];
draw(ch, s);

